version: "1.0"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: PGDB
    volumes:
      - ./data:/var/lib/postgresql/data 
  myapp:
    image: "alexandrec0sta/pd2223:latest"
    ports:
      - 3000:3000
    container_name: "myapp"