version: "1.0"

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: sql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${podemos meter aqui a password ou tem de ser hardcoded?}
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql