CREATE TABLE IF NOT EXISTS public.tle
(
	id VARCHAR(100) NOT NULL,
	type VARCHAR(50) NOT NULL,
	satelliteId INT PRIMARY KEY NOT NULL,
	name VARCHAR(100) NOT NULL,
	date DATE NOT NULL,
	line1 VARCHAR(200) NOT NULL,
	line2 VARCHAR(200) NOT NULL
);
